### ISSUE TITLE
sdist LICENSE and tests

### ISSUE THREAD

**Issue by jayvdb** [srossross/rpmfile#33]
LICENSE is missing from the PyPI sdist, and the tests rely on test data which is fetched from github, which fails when building an RPM.

**Comment by jayvdb** [comment]
Note 1.0.3 tag is also missing

**Comment by pdxjohnny** [comment]
[rpm-4.15.0-6.fc31.src.rpm.txt](https://github.com/srossross/rpmfile/files/5561331/rpm-4.15.0-6.fc31.src.rpm.txt)

Thanks for letting us know!
